// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKL2XA11UjmkmCNJ_P7UnAaPuBueuvqs4',
    appId: '1:412110770456:web:87647b3bdf2d78ecff8e6d',
    messagingSenderId: '412110770456',
    projectId: 'invoice-app-e3752',
    authDomain: 'invoice-app-e3752.firebaseapp.com',
    storageBucket: 'invoice-app-e3752.firebasestorage.app',
    measurementId: 'G-XP7DNXQQW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEsGCqgWjYJVw8i3_JItGPQToc6JgHnOk',
    appId: '1:412110770456:android:5816bdc1c7447eb2ff8e6d',
    messagingSenderId: '412110770456',
    projectId: 'invoice-app-e3752',
    storageBucket: 'invoice-app-e3752.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOwOxVxKvxtpawA_3gtiAhC1ump4TdVPI',
    appId: '1:412110770456:ios:854891ef3a30095dff8e6d',
    messagingSenderId: '412110770456',
    projectId: 'invoice-app-e3752',
    storageBucket: 'invoice-app-e3752.firebasestorage.app',
    iosBundleId: 'com.example.invoiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOwOxVxKvxtpawA_3gtiAhC1ump4TdVPI',
    appId: '1:412110770456:ios:854891ef3a30095dff8e6d',
    messagingSenderId: '412110770456',
    projectId: 'invoice-app-e3752',
    storageBucket: 'invoice-app-e3752.firebasestorage.app',
    iosBundleId: 'com.example.invoiceApp',
  );
}
